
package com.insp.service.distengine;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DistanceEngineService", targetNamespace = "http://xmlns.oracle.com/apps/otm/distanceengine", wsdlLocation = "file:/E:/InstalledSW/Jre-1.6-64/bin/DistanceEngineService.wsdl")
public class DistanceEngineService
    extends Service
{

    private final static URL DISTANCEENGINESERVICE_WSDL_LOCATION;
    private final static WebServiceException DISTANCEENGINESERVICE_EXCEPTION;
    private final static QName DISTANCEENGINESERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/otm/distanceengine", "DistanceEngineService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/InstalledSW/Jre-1.6-64/bin/DistanceEngineService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DISTANCEENGINESERVICE_WSDL_LOCATION = url;
        DISTANCEENGINESERVICE_EXCEPTION = e;
    }

    public DistanceEngineService() {
        super(__getWsdlLocation(), DISTANCEENGINESERVICE_QNAME);
    }

    public DistanceEngineService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DISTANCEENGINESERVICE_QNAME, features);
    }

    public DistanceEngineService(URL wsdlLocation) {
        super(wsdlLocation, DISTANCEENGINESERVICE_QNAME);
    }

    public DistanceEngineService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DISTANCEENGINESERVICE_QNAME, features);
    }

    public DistanceEngineService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DistanceEngineService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExternalDistanceEngine
     */
    @WebEndpoint(name = "ExternalDistanceEnginePort")
    public ExternalDistanceEngine getExternalDistanceEnginePort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/otm/distanceengine", "ExternalDistanceEnginePort"), ExternalDistanceEngine.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExternalDistanceEngine
     */
    @WebEndpoint(name = "ExternalDistanceEnginePort")
    public ExternalDistanceEngine getExternalDistanceEnginePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/otm/distanceengine", "ExternalDistanceEnginePort"), ExternalDistanceEngine.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DISTANCEENGINESERVICE_EXCEPTION!= null) {
            throw DISTANCEENGINESERVICE_EXCEPTION;
        }
        return DISTANCEENGINESERVICE_WSDL_LOCATION;
    }

}
