
package com.insp.service.distengine;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExternalDistanceEngine", targetNamespace = "http://xmlns.oracle.com/apps/otm/distanceengine")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExternalDistanceEngine {


    /**
     * 
     * @param lookupDistanceRequest
     * @return
     *     returns com.insp.service.distengine.ExtEngineDistance
     * @throws ExtEngineException
     */
    @WebMethod(action = "lookupDistance", exclude=true)
    @WebResult(name = "extEngineDistance", targetNamespace = "http://xmlns.oracle.com/apps/otm/distanceengine", partName = "extEngineDistance")
    public ExtEngineDistance lookupDistance(
        @WebParam(name = "lookupDistanceRequest", targetNamespace = "http://xmlns.oracle.com/apps/otm/distanceengine", partName = "lookupDistanceRequest")
        LookupDistanceRequest lookupDistanceRequest)
        throws ExtEngineException
    ;

    /**
     * 
     * @param validateAddressRequest
     * @return
     *     returns com.insp.service.distengine.LocationAddressMatches
     * @throws ExtEngineException
     */
    @WebMethod(action = "validateAddress")
    @WebResult(name = "locationAddressMatches", targetNamespace = "http://xmlns.oracle.com/apps/otm/distanceengine", partName = "locationAddressMatches")
    public LocationAddressMatches validateAddress(
        @WebParam(name = "validateAddressRequest", targetNamespace = "http://xmlns.oracle.com/apps/otm/distanceengine", partName = "validateAddressRequest")
        ValidateAddressRequest validateAddressRequest)
        throws ExtEngineException
    ;

}
